# Schema for the configuration files of the Convivial Content module.
convivial_content.settings:
  type: config_object
  label: 'Convivial Content settings'
  mapping:
    source_url:
      type: string
      label: 'Source URL'
      description: 'Enter the source URL to fetch the content.'
