# Schema for the configuration files of the Convivial Content module.
convivial_content.settings:
  type: config_object
  label: 'Convivial Content settings'
  mapping:
    consent_delete:
      type: boolean
      label: 'Delete Existing Content'
      description: 'Check to delete existing content.'
    sites:
      type: string
      label: 'Sites'
      description: 'Select the Site.'
    custom_yaml:
      type: string
      label: 'YAML'
      description: 'Custom YAML.'
    source:
      type: string
      label: 'Site Source'
      description: 'Site Source for the YAML file.'
